version: '3.4'

services:
  unicodepropertyaliasesecmascript:
    image: unicodepropertyaliasesecmascript
    build:
      context: node_modules/unicode-property-aliases-ecmascript
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
